"""aggregate_pools on a synthetic category shaped like blood: two pools with weights, per-donor
shares in one, a haemoglobin-like dominant set, an albumin-like dominant entry, a compartment mix
with hand-checkable numbers, and a tiny Monte Carlo. Every number is invented."""
import math

from pipeline import common, aggregate_pools as agp

AA = list(common.AMINO_ACIDS)


def read(path):
    return agp.read_commented_tsv(path)


def _frac(hi, val=0.5):
    f = {a: (1 - val) / 19 for a in AA}
    f[hi] = val
    return f


def _setup(tmp_path, monkeypatch):
    monkeypatch.setattr(common, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(common, "CONFIG_DIR", tmp_path / "config")
    monkeypatch.setattr(common, "DATA_DIR", tmp_path / "data")
    monkeypatch.setattr(common, "OUTPUTS_DIR", tmp_path / "outputs")
    monkeypatch.setattr(common, "LOGS_DIR", tmp_path / "logs")
    monkeypatch.setattr(common, "EAA_INI", tmp_path / "config" / "eaa.ini")
    monkeypatch.setattr(common, "AMINO_ACID_SYMBOLS_INI", tmp_path / "data" / "symbols.ini")
    monkeypatch.setattr(common, "UNCERTAINTY_SETTINGS_INI", tmp_path / "config" / "unc.ini")
    cfg = tmp_path / "config" / "cat"; cfg.mkdir(parents=True)
    (tmp_path / "data").mkdir(exist_ok=True)
    comp_dir = tmp_path / "outputs" / "cat" / "intermediate" / "composition"; comp_dir.mkdir(parents=True)
    mf_dir = tmp_path / "outputs" / "cat" / "intermediate" / "mass_fractions"; mf_dir.mkdir(parents=True)

    psd = common.new_ini(); psd["scope"] = {"category": "cat"}
    psd["pool.plasma"] = {"dataset_source": "s", "dataset_file": "file.1"}; psd["pool.erythrocytes"] = {"dataset_source": "s", "dataset_file": "file.2"}
    psd["contaminant_rules"] = {"keratin_keyword_id": "KW-0416"}
    common.write_ini(psd, cfg / "protein_set_decisions.ini", ["t"])

    # weights: plasma ALB 0.5 + X 0.5; erythrocytes HBB 0.6 (per donor .5/.6/.7/.6), Y 0.4
    hdr = ["accession", "gene", "tier", "mw_master"]
    for p in ("erythrocytes", "plasma"):
        hdr += [f"match_rule_{p}", f"n_rows_{p}", f"rows_{p}", f"v_{p}", f"sd_{p}", f"n_{p}", f"published_share_{p}", f"shared_row_value_{p}", f"w_{p}", f"w_{p}_low", f"w_{p}_high"]
        if p == "erythrocytes":
            hdr += [f"v_{p}_rep1", f"v_{p}_rep2", f"v_{p}_rep3", f"v_{p}_rep4"]
        else:
            hdr += [f"cv_percent_published_{p}"]
    blank_e = [""] * 15
    blank_p = [""] * 12
    rows = [
        ["P00001", "ALB", "plasma", "66000"] + blank_e + ["single", "1", "2", "0.5", "0.05", "15", "0.5", "0", "0.5", "0.45", "0.55", "4"],
        ["P00002", "XX", "plasma", "50000"] + blank_e + ["single", "1", "3", "0.5", "0.05", "15", "0.5", "0", "0.5", "0.45", "0.55", "4"],
        ["P00003", "HBB", "erythrocytes", "16000"] + ["single", "1", "2", "0.6", "0.08165", "4", "0.6", "0", "0.6", "0.52", "0.68", "0.5", "0.6", "0.7", "0.6"] + blank_p,
        ["P00004", "YY", "erythrocytes", "30000"] + ["single", "1", "3", "0.4", "0.08165", "4", "0.4", "0", "0.4", "0.32", "0.48", "0.5", "0.4", "0.3", "0.4"] + blank_p,
    ]
    (cfg / "mass_fractions_per_entry.tsv").write_text("# GENERATED by mass_fractions_pools.py\n" + "\t".join(hdr) + "\n" + "\n".join("\t".join(r) for r in rows) + "\n")

    comp_header = ["accession", "gene", "tier", "segment_set", "n_residues", "residue_mass_sum", "mw", "free_mass_sum"] + [f"count_{a}" for a in AA] \
        + [f"residue_frac_{a}" for a in AA] + [f"free_frac_{a}" for a in AA]
    fr = {"P00001": _frac("C", 0.4), "P00002": _frac("A", 0.4), "P00003": _frac("H", 0.4), "P00004": _frac("L", 0.4)}
    comp_rows = [[acc, "", "", "master", "100", "1", "1", "1"] + ["0"] * 20 + [f"{fr[acc][a]:.6f}" for a in AA] + [f"{fr[acc][a]:.6f}" for a in AA] for acc in fr]
    common.write_tsv(comp_dir / "amino_acid_composition_per_protein.tsv", comp_header, comp_rows)

    common.write_tsv(mf_dir / "weighted_bounds.tsv", ["pool", "kind", "amino_acid", "max_weighted_delta", "where"],
                     [["plasma", "isoform", "C", "0.002", "P00001"], ["plasma", "ptm_mass", "all", "0.01", "P00001"], ["erythrocytes", "isoform", "H", "0.001", "P00003"]])
    common.write_tsv(mf_dir / "immunoglobulin_variable_domain_bound_per_chain.tsv",
                     ["pool", "chain", "n_constant_entries", "constant_entries_w", "L_V_mean_residues", "n_V_entries", "variable_entries_w_measured", "variable_mass_bound", "loose_bound_whole_share"],
                     [["plasma", "all", "1", "0.1", "", "", "0", "0.03", "0.1"], ["erythrocytes", "all", "0", "0", "", "", "0", "0", "0"]])
    summ = common.new_ini()
    summ["pool.plasma"] = {"completeness_gap_share_of_listing": "0.002"}; summ["pool.erythrocytes"] = {"completeness_gap_share_of_listing": "0.001"}
    common.write_ini(summ, mf_dir / "mass_fractions_summary.ini", ["t"])

    mix = """[reference]
sex = male
[compartment.plasma]
volume_ml = 3000
volume_location = t
volume_ml_female = 2400
protein_g_per_l = 70
[compartment.erythrocytes]
volume_ml = 2000
volume_location = t
volume_ml_female = 1500
mchc_g_per_l = 300
blood_hb_g_per_l = 150
[dominant.erythrocytes]
genes = HBB, HBA1
share.other = 0.8
share.other.location = t
share.implied = computed
share.implied.location = t
[dominant.plasma]
genes = ALB
share.clinical = 0.6
share.clinical.location = t
[cross_check.whole_blood_protein]
blood_mass_g = 5000
protein_fraction = 0.2
"""
    (cfg / "compartment_mix.ini").write_text(mix)
    (tmp_path / "config" / "eaa.ini").write_text("[indispensable_amino_acids]\nheadings = His, Leu, SAA\nlocation = t\n[group.SAA]\nmembers = Met, Cys\n")
    three = {"A": "Ala", "C": "Cys", "D": "Asp", "E": "Glu", "F": "Phe", "G": "Gly", "H": "His", "I": "Ile", "K": "Lys", "L": "Leu",
             "M": "Met", "N": "Asn", "P": "Pro", "Q": "Gln", "R": "Arg", "S": "Ser", "T": "Thr", "V": "Val", "W": "Trp", "Y": "Tyr"}
    (tmp_path / "data" / "symbols.ini").write_text("".join(f"[{a}]\nthree_letter = {t}\n" for a, t in three.items()))
    (tmp_path / "config" / "unc.ini").write_text("[monte_carlo]\ndraws = 400\nseed = 1\n")


def test_standard_split_sensitivities_and_drivers(tmp_path, monkeypatch):
    _setup(tmp_path, monkeypatch)
    assert agp.main(["--category", "cat"]) == 0
    out = tmp_path / "outputs" / "cat" / "standard"
    summ = common.read_ini(out / "standard_summary.ini")
    # the split: plasma 3.0 L x 70 = 210 g; Hb = 2.0 L x 300 = 600 g; measured Hb share 0.6 -> erythrocyte protein 1000 g; f_plasma = 210/1210
    sp = summ["split"]
    assert float(sp["plasma_protein_g"]) == 210 and float(sp["haemoglobin_g"]) == 600
    assert math.isclose(float(sp["haemoglobin_share_as_measured"]), 0.6) and math.isclose(float(sp["erythrocyte_protein_g"]), 1000)
    assert math.isclose(float(sp["f_plasma"]), 210 / 1210)
    assert math.isclose(float(sp["haemoglobin_g_blood_route"]), 5.0 * 150)
    # the implied share: 600 / (5000 x 0.2 - 210) = 600 / 790
    assert sp["f_plasma_at_hb_share_implied"].startswith(agp.fnum(210 / (210 + 790))[:6])
    # the standard: His = f x plasma_His + (1-f) x ery_His; plasma His = 100 x (0.5 x 0.6/19 x ... ) hand: each non-dominant aa frac = 0.6/19
    f = 210 / 1210
    plasma_h = 100 * (0.5 * 0.6 / 19 + 0.5 * 0.6 / 19)
    ery_h = 100 * (0.6 * 0.4 + 0.4 * 0.6 / 19)
    std = {r["amino_acid"]: r for r in read(out / "_calculated_amino_acid_standard.tsv")}
    assert math.isclose(float(std["H"]["total_plasma"]), plasma_h, rel_tol=1e-4) and math.isclose(float(std["H"]["total_erythrocytes"]), ery_h, rel_tol=1e-4)
    assert math.isclose(float(std["H"]["standard"]), f * plasma_h + (1 - f) * ery_h, rel_tol=1e-4)
    assert math.isclose(sum(float(r["standard"]) for r in std.values()), 100.0, rel_tol=1e-4)
    # D117: at Hb share 0.8 the erythrocyte profile has HBB at 0.8 and the mass 750 g
    sens = {(r["hb_share_label"], r["albumin_share_label"], r["convention"], r["amino_acid"]): r for r in read(out / "sensitivity_dominant_protein.tsv")}
    r = sens[("other", "as_measured", "free", "H")]
    assert math.isclose(float(r["profile_erythrocytes"]), 100 * (0.8 * 0.4 + 0.2 * 0.6 / 19), rel_tol=1e-4)
    assert math.isclose(float(r["f_plasma"]), 210 / (210 + 750), rel_tol=1e-4)
    r = sens[("as_measured", "clinical", "free", "C")]
    assert math.isclose(float(r["profile_plasma"]), 100 * (0.6 * 0.4 + 0.4 * 0.6 / 19), rel_tol=1e-4)
    assert sens[("as_measured", "as_measured", "free", "H")]["standard_minus_base"] == "0"
    spread = {(r["convention"], r["amino_acid"]): r for r in read(out / "sensitivity_dominant_protein_spread.tsv")}
    assert float(spread[("free", "H")]["spread_haemoglobin_only"]) > 0 and float(spread[("free", "C")]["spread_albumin_only"]) > 0
    # D108: donor 3 has HBB at 0.7
    donors = {(r["pool"], r["weights"], r["convention"], r["amino_acid"]): r for r in read(out / "sensitivity_per_donor.tsv")}
    assert math.isclose(float(donors[("erythrocytes", "donor_3", "free", "H")]["profile_pool"]), 100 * (0.7 * 0.4 + 0.3 * 0.6 / 19), rel_tol=1e-4)
    assert math.isclose(float(donors[("erythrocytes", "mean_of_donors (the weight)", "free", "H")]["profile_pool"]), ery_h, rel_tol=1e-4)
    # uncertainty and terms
    unc = read(out / "uncertainty_intervals.tsv")
    assert {r["profile"] for r in unc} == {"plasma", "erythrocytes", "standard"} and all(float(r["half_width"]) >= 0 for r in unc)
    terms = {(r["profile"], r["convention"], r["amino_acid"]): r for r in read(out / "uncertainty_per_amino_acid.tsv")}
    t = terms[("standard", "free", "C")]
    assert math.isclose(float(t["bound_isoform"]), 100 * f * 0.002, rel_tol=1e-4) and math.isclose(float(t["bound_ig_variable_domain"]), 100 * f * 0.03, rel_tol=1e-4)
    assert math.isclose(float(t["bound_completeness_gap"]), 100 * (f * 0.002 + (1 - f) * 0.001), rel_tol=1e-4)
    assert t["widest_term"] in t
    # drivers: HBB carries the standard's histidine
    his = [r for r in read(out / "histidine_drivers.tsv") if r["profile"] == "standard"]
    assert his[0]["gene"] == "HBB" and float(his[0]["share_of_histidine"]) > 0.9
    assert summ["histidine"]["widest_term_standard"] and float(summ["histidine"]["haemoglobin_entries_share_of_standard_histidine"]) > 0.9
    eaa = {r["heading"]: r for r in read(out / "eaa_subset.tsv")}
    assert eaa["SAA"]["amino_acids"] == "M+C"
    fem = [r for r in read(out / "compartment_split.tsv") if r["haemoglobin_share"].startswith("female")]
    assert fem and math.isclose(float(fem[0]["plasma_protein_g"]), 2.4 * 70)
    for name in ("profile_pools_and_standard.png", "sensitivity_dominant_protein.png", "uncertainty_terms_standard.png"):
        assert (out / "plots" / name).stat().st_size > 1000
    assert agp.main(["--category", "cat", "--check"]) == 0
    p = out / "_calculated_amino_acid_standard.tsv"
    p.write_text(p.read_text().replace("total_plasma", "total_plasmaX"))
    assert agp.main(["--category", "cat", "--check"]) == 1
