"""build_protein_set and isoform_processing_deltas with --category, offline, on a synthetic store,
pool tables and decisions file (Step 7b). Also pins the muscle wording helpers so the muscle
accessions.ini keeps its Step 1 / D56 text byte for byte."""
import json

from conftest import FIXTURES

from pipeline import common, build_protein_set as bp, fetch_sequences as fs, isoform_processing_deltas as ipd
from pipeline import composition as comp, ptm_disclosure as ptm


def _store(tmp_path, accs):
    entry = json.loads((FIXTURES / "entry_one_chain.json").read_text())
    cp = common.new_ini()
    for acc, extra in accs.items():
        e = json.loads(json.dumps(entry)); e["primaryAccession"] = acc
        rec = fs.extract(e); fs.check_sequence(rec, rec["sequence"]); rec["canonical_isoform_id"] = f"{acc}-1"
        sec = fs.to_section(rec, ["1"]); sec.update(extra); cp[acc] = sec
    common.write_ini(cp, tmp_path / "data" / "uniprot_sequences.ini", [
        "uniprot_sequences.ini -- GENERATED by fetch_sequences.py. DO NOT EDIT BY HAND.",
        "fetched         = 2026-01-01T00:00:00Z", "uniprot_release = 2026_03", "accessions      = 2", "failures        = 0"])


def _category(tmp_path, monkeypatch):
    monkeypatch.setattr(common, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(common, "CONFIG_DIR", tmp_path / "config")
    monkeypatch.setattr(common, "DATA_DIR", tmp_path / "data")
    monkeypatch.setattr(common, "OUTPUTS_DIR", tmp_path / "outputs")
    monkeypatch.setattr(common, "LOGS_DIR", tmp_path / "logs")
    monkeypatch.setattr(common, "SEQUENCES_INI", tmp_path / "data" / "uniprot_sequences.ini")
    monkeypatch.setattr(common, "UNIPROT_RAW_DIR", tmp_path / "data" / "uniprot_raw")
    (tmp_path / "config" / "cat").mkdir(parents=True); (tmp_path / "data" / "cat").mkdir(parents=True)
    _store(tmp_path, {"X99001": {}, "X99002": {"fetched": "2026-09-19T00:00:00Z", "uniprot_release": "2026_04"}})
    psd = common.new_ini()
    psd["scope"] = {"category": "cat"}
    psd["pool.red"] = {"dataset_source": "src", "dataset_file": "file.1", "pool_decision": "D107", "contaminant_decision": "D98"}
    psd["pool.yellow"] = {"dataset_source": "src2", "dataset_file": "file.1", "pool_decision": "D107", "contaminant_decision": "D98"}
    psd["contaminant_rules"] = {"keratin_keyword_id": "KW-0416"}
    common.write_ini(psd, tmp_path / "config" / "cat" / "protein_set_decisions.ini", ["test"])
    cols = ["accession", "gene_primary", "protein_name", "length", "reviewed", "organism_id", "dataset_rows", "identity_cell"]
    common.write_tsv(tmp_path / "data" / "cat" / "pool_red.tsv", cols, [["X99001", "FIXA", "a", "13", "reviewed", "9606", "3", "X99001"],
                                                                          ["X99002", "FIXA", "a", "13", "reviewed", "9606", "4", "X99002"]])
    common.write_tsv(tmp_path / "data" / "cat" / "pool_yellow.tsv", cols, [["X99002", "FIXA", "a", "13", "reviewed", "9606", "9", "X99002"]])
    q = common.new_ini()
    q["run"] = {"date": "2026-09-19T00:00:00Z", "category": "cat"}
    q["pool.red"] = {"dataset_sha256": "abc", "keratin_keyword_id": "KW-0416", "named_contaminant_genes": "(none)"}
    q["pool.yellow"] = {"dataset_sha256": "def", "keratin_keyword_id": "KW-0416", "named_contaminant_genes": "ALB"}
    common.write_ini(q, tmp_path / "data" / "cat" / "pool_queries.ini", ["test"])


def test_category_build_writes_config_and_tables_under_the_category(tmp_path, monkeypatch):
    _category(tmp_path, monkeypatch)
    assert bp.main(["--category", "cat"]) == 0
    acc = common.read_ini(tmp_path / "config" / "cat" / "accessions.ini")
    assert set(acc.sections()) == {"X99001", "X99002"}
    assert acc["X99001"]["tier"] == "red" and acc["X99002"]["tier"] == "red;yellow"
    assert acc["X99001"]["pool_membership"].startswith("computed: red = quantified set of src file.1 (D107) minus its contaminant rule (D98)")
    assert "yellow = quantified set of src2 file.1" in acc["X99002"]["pool_membership"]
    assert acc["X99001"]["subtree_annotations"] == "red: (measured set; no ontology category)"
    # a section a category added carries its own fetch record; the others fall back to the store header
    assert acc["X99002"]["fetched"] == "2026-09-19T00:00:00Z" and acc["X99002"]["uniprot_release"] == "2026_04"
    assert acc["X99001"]["fetched"] == "2026-01-01T00:00:00Z" and acc["X99001"]["uniprot_release"] == "2026_03"
    head = (tmp_path / "config" / "cat" / "accessions.ini").read_text().splitlines()
    assert head[0].startswith("# GENERATED by build_protein_set.py")
    assert any(l.startswith("# category              = cat") for l in head)
    assert any(l.startswith("# pool red: quantified set of src file.1 (sha256 abc)") and "pool size 2" in l for l in head)
    assert any("named genes ALB" in l for l in head)
    seg = common.read_ini(tmp_path / "config" / "cat" / "segments.ini")
    assert seg["X99001.master"]["in_master_molecule"] == "true"
    out = tmp_path / "outputs" / "cat" / "intermediate" / "protein_set"
    assert (out / "evidence_summary.tsv").exists() and (out / "excluded_non_standard_alphabet.tsv").exists()
    ev = common.read_tsv(out / "evidence_summary.tsv")
    assert all(r["evidence_code"] == "(measured set; no ontology annotation applies)" for r in ev)
    assert (tmp_path / "outputs" / "cat" / "flags.tsv").exists() is False or common.read_tsv(tmp_path / "outputs" / "cat" / "flags.tsv") == []
    # nothing landed in the muscle locations
    assert not (tmp_path / "config" / "accessions.ini").exists() and not (tmp_path / "outputs" / "flags.tsv").exists()
    # the currency check passes on what was just written, and fails after a hand edit
    assert bp.main(["--category", "cat", "--check"]) == 0
    p = tmp_path / "config" / "cat" / "accessions.ini"
    p.write_text(p.read_text().replace("tier                 = red;yellow", "tier                 = yellow"))
    assert bp.main(["--category", "cat", "--check"]) == 1
    # the deltas stage writes beside the build tables
    bp.main(["--category", "cat"])
    assert ipd.main(["--category", "cat"]) == 0
    assert (out / "isoform_bound.tsv").exists() and (out / "processing_deltas.tsv").exists()
    rows = common.read_tsv(out / "processing_deltas.tsv")
    assert {r["tier"] for r in rows} == {"red", "red;yellow"}


def test_category_composition_writes_under_the_category(tmp_path, monkeypatch):
    """composition and ptm_disclosure with --category: the category's accessions and segments in,
    outputs/<category>/intermediate/composition/ out, the raw entries found in the nested folder."""
    _category(tmp_path, monkeypatch)
    masses = tmp_path / "data" / "pubchem" / "amino_acid_masses.ini"
    masses.parent.mkdir(parents=True)
    masses.write_text((FIXTURES / "masses_synthetic.ini").read_text(encoding="utf-8"), encoding="utf-8")
    monkeypatch.setattr(common, "AMINO_ACID_MASSES_INI", masses)
    ptmlist = tmp_path / "data" / "uniprot_ptmlist" / "ptmlist.txt"
    ptmlist.parent.mkdir(parents=True)
    ptmlist.write_text((FIXTURES / "ptmlist_synthetic.txt").read_text(encoding="utf-8"), encoding="utf-8")
    src = common.new_ini(); src["ptmlist"] = {"url": "test", "sha256": "0", "retrieved": "now"}
    common.write_ini(src, ptmlist.parent / "source.ini", ["test"])
    monkeypatch.setattr(common, "PTMLIST_TXT", ptmlist)
    raw = tmp_path / "data" / "uniprot_raw" / "cat"
    raw.mkdir(parents=True)
    entry = json.loads((FIXTURES / "entry_one_chain.json").read_text())
    for acc in ("X99001", "X99002"):
        e = json.loads(json.dumps(entry)); e["primaryAccession"] = acc
        (raw / f"{acc}.json").write_text(json.dumps(e), encoding="utf-8")
    assert bp.main(["--category", "cat"]) == 0
    assert comp.main(["--category", "cat"]) == 0
    cdir = tmp_path / "outputs" / "cat" / "intermediate" / "composition"
    assert (cdir / "amino_acid_composition_per_protein.tsv").exists() and (cdir / "composition_summary.ini").exists()
    head = (cdir / "composition_summary.ini").read_text().splitlines()
    assert any(l.startswith("# category          = cat") for l in head)
    assert any(l.startswith("# segments          = config/cat/segments.ini") for l in head)
    rows = common.read_tsv(cdir / "amino_acid_composition_per_protein.tsv")
    assert {r["accession"] for r in rows} == {"X99001", "X99002"}
    assert comp.main(["--category", "cat", "--check"]) == 0
    assert ptm.main(["--category", "cat"]) == 0
    assert (cdir / "ptm_sites.tsv").exists() and (cdir / "ptm_summary.ini").exists()
    deltas = common.read_tsv(cdir / "ptm_mass_deltas.tsv")
    assert {r["tier"] for r in deltas} == {"red", "red;yellow"}
    assert not (tmp_path / "outputs" / "intermediate").exists()          # nothing landed in the muscle tree


def test_muscle_wording_is_unchanged():
    """The strings the muscle accessions.ini has carried since Step 1 (ontology tier) and D56 (measured tier)."""
    resolved = common.new_ini()
    resolved["tier.1"] = {"term_id": "GO:0030016", "term_name": "myofibril", "seed_word": "myofibrillar", "seed_decision": "D3",
                          "lookup_name": "myofibril", "lookup_decision": "D13"}
    resolved["tier.2"] = {"definition": "measured_remainder", "definition_decision": "D56", "dataset_source": "murgia_2021",
                          "dataset_file": "file.1", "contaminant_source": "contaminants_maxquant", "seed_word": "the rest", "seed_decision": "D4"}
    pools = {"1": [{"accession": "A"}], "2": [{"accession": "B"}, {"accession": "C"}]}
    subtrees = {"1": {"GO:0030016"}}
    m = bp.muscle_membership_text(resolved, pools, subtrees)
    assert m["1"] == "tier 1 = subtree of GO:0030016 (myofibril)"
    assert m["2"] == "tier 2 = measured remainder of murgia_2021 (D56)"
    lines = bp.muscle_pool_lines(resolved, pools, subtrees)
    assert lines[0] == "tier 1: seed_word=myofibrillar (D3) lookup_name=myofibril (D13) -> GO:0030016 myofibril ; pool size 1"
    assert lines[1] == ("tier 2: seed_word=the rest (D4) definition=measured_remainder (D56) from murgia_2021 file.1 "
                        "minus contaminants_maxquant ; pool size 2")
