"""The blood mass-fraction outputs and generated config must equal a fresh build (Step 7b).

Skipped until `python run.py blood-mass-fractions` has run on this machine, and while an earlier
command is running (blood-composition rebuilds what this reads).
"""
import pytest

from pipeline import common, mass_fractions_pools

FILES = common.category_files("blood")

needs_run = pytest.mark.skipif(
    not FILES["mass_fractions_tsv"].exists() or not FILES["composition_tsv"].exists()
    or common.running_command_is_before("blood-mass-fractions"),
    reason="blood-mass-fractions not run yet on this machine, or an earlier command is running")


@needs_run
def test_blood_mass_fraction_outputs_are_current():
    assert mass_fractions_pools.main(["--category", "blood", "--check"]) == 0


@needs_run
def test_blood_weights_sum_to_one_per_pool():
    lines = [l for l in FILES["mass_fractions_tsv"].read_text(encoding="utf-8").splitlines() if not l.startswith("#")]
    hdr = lines[0].split("\t")
    rows = [dict(zip(hdr, l.split("\t"))) for l in lines[1:] if l]
    for pool in common.pool_names("blood"):
        s = sum(float(r[f"w_{pool}"]) for r in rows if r[f"w_{pool}"])
        assert abs(s - 1.0) < 1e-9, (pool, s)


@needs_run
def test_blood_generated_config_is_marked():
    assert FILES["mass_fractions_tsv"].read_text(encoding="utf-8").startswith("# GENERATED by mass_fractions_pools.py")
