"""The blood category's generated config must equal a fresh build from the data on disk (Step 7b).

Skipped until `python run.py blood-protein-set` has run on this machine (no config/blood/accessions.ini).
Skipped while an EARLIER command is running: blood is rebuilt by its own command.
"""
import pytest

from pipeline import common, build_protein_set
from pipeline.flags import open_flags

FILES = common.category_files("blood")

needs_run = pytest.mark.skipif(
    not FILES["accessions"].exists() or not FILES["pool_queries"].exists() or common.running_command_is_before("blood-protein-set"),
    reason="blood-protein-set not run yet on this machine, or an earlier command is running")


@needs_run
def test_blood_generated_config_is_current():
    assert build_protein_set.main(["--category", "blood", "--check"]) == 0


@needs_run
def test_blood_has_no_open_flags():
    decisions = common.read_ini(FILES["decisions"])
    assert open_flags(FILES["flags"], decisions) == []


@needs_run
def test_blood_config_files_are_generated():
    for p in (FILES["accessions"], FILES["segments"]):
        assert p.read_text(encoding="utf-8").startswith("# GENERATED by build_protein_set.py")


@needs_run
def test_blood_pool_tables_exist_for_every_declared_pool():
    for pool in common.pool_names("blood"):
        assert common.pool_file("blood", pool).exists(), pool
        assert (FILES["pool_dir"] / f"{pool}_dataset_rows.tsv").exists(), pool
        assert (FILES["pool_dir"] / f"{pool}_rows_excluded_with_share.tsv").exists(), pool


def test_blood_decisions_file_names_only_what_d98_names():
    """The hand-written file holds the scope, the pools, the contaminant rules and flag closures.
    The only protein names in it are the D98 contaminants, each with a page location beside it."""
    if not FILES["decisions"].exists():
        pytest.skip("config/blood/protein_set_decisions.ini not present")
    cp = common.read_ini(FILES["decisions"])
    for s in cp.sections():
        assert s in ("scope", "contaminant_rules") or s.startswith(("pool.", "flag.")), s
    assert cp["scope"]["category"] == "blood"
    for s in cp.sections():
        if s.startswith("pool."):
            sec = cp[s]
            assert sec["dataset_source"] and sec["dataset_file"]
            if sec.get("named_contaminant_genes", "").strip():
                assert sec.get("named_contaminant_location", "").strip(), f"{s}: named genes need their page location"
    assert cp["contaminant_rules"]["keratin_keyword_id"].startswith("KW-")
