"""The generated config must equal a fresh build from the data on disk.

Skipped when the network stages have not yet been run on this machine (no
data/uniprot_sequences.ini). Fails if config/accessions.ini or segments.ini
was hand-edited or is stale, or if any flag is still open.
"""
import pytest

from pipeline import common, build_protein_set
from pipeline.flags import open_flags


needs_data = pytest.mark.skipif(
    not common.SEQUENCES_INI.exists() or not common.RESOLVED_TERMS_INI.exists(),
    reason="network stages not run yet; no fetched data on disk")


@needs_data
def test_generated_config_is_current():
    assert build_protein_set.main(["--check"]) == 0


@needs_data
def test_no_open_flags():
    decisions = common.read_ini(common.DECISIONS_INI)
    assert open_flags(common.FLAGS_TSV, decisions) == []


@needs_data
def test_config_files_are_not_hand_edited_markers():
    for p in (common.ACCESSIONS_INI, common.SEGMENTS_INI):
        assert p.read_text(encoding="utf-8").startswith("# GENERATED by build_protein_set.py")


def test_decisions_file_contains_no_protein_list():
    """The hand-written file may name tiers, seeds, the ontology source, and flag
    closures -- nothing else."""
    cp = common.read_ini(common.DECISIONS_INI)
    for s in cp.sections():
        assert s == "ontology_source" or s.startswith("tier.") or s.startswith("flag."), s
