"""composite.py on a synthetic pair of categories with hand-checkable numbers.

muscle: 3 kg of tissue at 200 g protein/kg -> 600 g protein; its profile is 4 % H.
blood:  a split table whose base row says 400 g protein; its profile is 10 % H.
Composite = 0.6 x muscle + 0.4 x blood -> H = 0.6 x 4 + 0.4 x 10 = 6.4. Every number is invented.
"""
import pytest

from pipeline import common, composite

AA = list(common.AMINO_ACIDS)


def _profile(hi: str, val: float) -> dict[str, float]:
    p = {a: (100 - val) / 19 for a in AA}
    p[hi] = val
    return p


def _table(path, column, prof, extra_cols=()):
    hdr = ["amino_acid"] + list(extra_cols) + [column]
    rows = [[a] + ["x"] * len(extra_cols) + [f"{prof[a]:.6f}"] for a in AA]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# GENERATED by test\n# generated = t\n" + "\t".join(hdr) + "\n" + "\n".join("\t".join(r) for r in rows) + "\n")


@pytest.fixture
def repo(tmp_path, monkeypatch):
    monkeypatch.setattr(common, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(common, "CONFIG_DIR", tmp_path / "config")
    monkeypatch.setattr(common, "DATA_DIR", tmp_path / "data")
    monkeypatch.setattr(common, "OUTPUTS_DIR", tmp_path / "outputs")
    monkeypatch.setattr(common, "LOGS_DIR", tmp_path / "logs")
    monkeypatch.setattr(common, "EAA_INI", tmp_path / "config" / "eaa.ini")
    monkeypatch.setattr(common, "AMINO_ACID_SYMBOLS_INI", tmp_path / "data" / "symbols.ini")
    monkeypatch.setattr(common, "AMINO_ACID_MASSES_INI", tmp_path / "data" / "masses.ini")
    monkeypatch.setattr(common, "FIBER_TYPE_MIX_INI", tmp_path / "config" / "mix.ini")
    monkeypatch.setattr(composite, "CONFIG_INI", tmp_path / "config" / "tissue_mass_fractions.ini")
    monkeypatch.setattr(composite, "OUT_DIR", tmp_path / "outputs" / "composite")
    (tmp_path / "config").mkdir(); (tmp_path / "data").mkdir()

    # symbols, masses (free = residue + 18 so the L4 factor is > 1 and hand-checkable), the EAA headings
    three = {a: f"X{a}" for a in AA}
    (tmp_path / "data" / "symbols.ini").write_text("".join(f"[{a}]\nthree_letter = {t}\ntrivial_name = name{a}\n" for a, t in three.items()))
    (tmp_path / "data" / "masses.ini").write_text("".join(f"[{a}]\nfree_mass = 118\nresidue_mass = 100\n" for a in AA))
    (tmp_path / "config" / "eaa.ini").write_text("[indispensable_amino_acids]\nheadings = XH, XL, SAA\nlocation = t\n[group.SAA]\nmembers = XM, XC\n")
    (tmp_path / "config" / "mix.ini").write_text("[shares]\nI = 0.5\nII = 0.5\nbasis = t\n")

    # muscle: the standard (4 % H), a residue table, the protein content section, a pool amounts table
    _table(tmp_path / "outputs" / "standard" / "muscle_with_pool.tsv", "standard_with_pool", _profile("H", 4.0), ["three_letter", "name"])
    _table(tmp_path / "outputs" / "standard" / "muscle_residue.tsv", "standard", _profile("H", 3.5))
    (tmp_path / "config" / "pools.ini").write_text("[protein_content]\nvalue = 200\nspread = 10\nbasis = wet\nsource_id = s\nlocation = p. 1\n")
    (tmp_path / "outputs" / "standard" / "amounts.tsv").write_text(
        "# GENERATED\nfiber_type\tpool_His_g_per_kg\tprotein_g_per_kg\nI\t2\t500\nII\t3\t500\n")     # ratios 0.004 and 0.006 -> mixed 0.005

    # blood: the standard (10 % H), its residue table, a split with a base row, a female row and one more row, and a D117-shaped sensitivity table
    _table(tmp_path / "outputs" / "blood" / "blood.tsv", "standard", _profile("H", 10.0))
    _table(tmp_path / "outputs" / "blood" / "blood_residue.tsv", "standard", _profile("H", 9.0))
    (tmp_path / "outputs" / "blood" / "split.tsv").write_text(
        "# GENERATED\nhaemoglobin_share\tshare\twhole_blood_protein_g\tshare_source\n"
        "as_measured\t0.5\t400\tmeasured\nother\t0.8\t250\tpublished\nfemale as_measured\t0.5\t300\tfemale\n")
    sens = ["# GENERATED", "\t".join(["hb_share_label", "hb_share", "albumin_share_label", "albumin_share", "convention", "amino_acid", "standard"])]
    for hl, hs, prof in (("as_measured", 0.5, _profile("H", 10.0)), ("other", 0.8, _profile("H", 20.0))):
        for al, as_ in (("as_measured", 0.2),):
            for conv in ("free", "residue"):
                for a in AA:
                    sens.append("\t".join([hl, str(hs), al, str(as_), conv, a, f"{prof[a]:.6f}"]))
    (tmp_path / "outputs" / "blood" / "sens.tsv").write_text("\n".join(sens) + "\n")

    (tmp_path / "config" / "tissue_mass_fractions.ini").write_text("""[meta]
reference_sex = male
[category.muscle]
label = m
standard_file = outputs/standard/muscle_with_pool.tsv
standard_column = standard_with_pool
residue_file = outputs/standard/muscle_residue.tsv
residue_column = standard
protein_mass = tissue_mass_x_protein_content
tissue_mass_g = 3000
tissue_mass_g_female = 2000
tissue_mass_location = t
protein_content_from = config/pools.ini [protein_content]
protein_content_basis = wet
non_protein_metabolite_pool_amounts = outputs/standard/amounts.tsv
fiber_type_mix = config/mix.ini
[category.blood]
label = b
standard_file = outputs/blood/blood.tsv
standard_column = standard
residue_file = outputs/blood/blood_residue.tsv
residue_column = standard
protein_mass = category_split
split_file = outputs/blood/split.tsv
split_column = whole_blood_protein_g
split_base_row = as_measured
split_female_prefix = female
tissue_mass_g = 5000
tissue_mass_g_female = 4000
tissue_mass_location = t
sensitivity_file = outputs/blood/sens.tsv
sensitivity_row_column = hb_share_label
sensitivity_row_share_column = hb_share
sensitivity_variant_column = albumin_share_label
sensitivity_variant_share_column = albumin_share
sensitivity_profile_column = standard
""")
    return tmp_path


def _rows(path):
    return composite.read_commented_tsv(path)


def test_composite_is_the_protein_mass_weighted_mix(repo):
    assert composite.main([]) == 0
    out = repo / "outputs" / "composite"
    rows = {r["amino_acid"]: r for r in _rows(out / "_calculated_amino_acid_standard_composite.tsv")}
    assert float(rows["H"]["muscle"]) == pytest.approx(4.0)
    assert float(rows["H"]["blood"]) == pytest.approx(10.0)
    assert float(rows["H"]["composite"]) == pytest.approx(0.6 * 4 + 0.4 * 10)          # 600 g : 400 g
    assert sum(float(r["composite"]) for r in rows.values()) == pytest.approx(100.0, abs=1e-6)
    masses = {(r["category"], r["sex"]): r for r in _rows(out / "category_protein_masses.tsv")}
    assert float(masses[("muscle", "male")]["protein_g"]) == pytest.approx(600.0)     # 3000 g x 200 g/kg / 1000
    assert float(masses[("blood", "male")]["share_of_composite"]) == pytest.approx(0.4)
    assert float(masses[("muscle", "female")]["protein_g"]) == pytest.approx(400.0)
    assert float(masses[("blood", "female")]["protein_g"]) == pytest.approx(300.0)
    assert composite.main(["--check"]) == 0


def test_contributions_sum_to_the_composite_and_split_the_histidine(repo):
    composite.main([])
    rows = {r["amino_acid"]: r for r in _rows(repo / "outputs" / "composite" / "category_contributions.tsv")}
    h = rows["H"]
    assert float(h["g_from_muscle"]) == pytest.approx(2.4) and float(h["g_from_blood"]) == pytest.approx(4.0)
    assert float(h["fraction_from_blood"]) == pytest.approx(4.0 / 6.4)


def test_sensitivity_moves_the_mass_with_the_share(repo):
    """L3: the `other` row of the split puts blood at 250 g with a 20 % H profile:
    f_blood = 250 / 850, composite H = (600 x 4 + 250 x 20) / 850."""
    composite.main([])
    rows = _rows(repo / "outputs" / "composite" / "sensitivity_category_split.tsv")
    base = [r for r in rows if r["split_row"] == "as_measured" and r["sex"] == "male" and r["amino_acid"] == "H"][0]
    assert float(base["composite"]) == pytest.approx(6.4) and float(base["composite_minus_base"]) == pytest.approx(0.0)
    other = [r for r in rows if r["split_row"] == "other" and r["sex"] == "male" and r["amino_acid"] == "H"][0]
    assert float(other["category_protein_g"]) == pytest.approx(250.0)
    assert float(other["composite"]) == pytest.approx((600 * 4 + 250 * 20) / 850)
    female = [r for r in rows if r["split_row"] == "as_measured" and r["sex"] == "female" and r["amino_acid"] == "H"][0]
    assert float(female["composite"]) == pytest.approx((400 * 4 + 300 * 10) / 700)      # female masses, same profiles
    assert float(female["composite_minus_base"]) == pytest.approx(0.0)
    spread = {r["amino_acid"]: r for r in _rows(repo / "outputs" / "composite" / "sensitivity_category_split_spread.tsv")}
    assert float(spread["H"]["max"]) == pytest.approx((600 * 4 + 250 * 20) / 850)


def test_weighting_by_amino_acid_mass_uses_the_factor_and_the_pool(repo):
    """L4: every residue becomes 118/100 of itself, so both factors are 1.18; muscle adds the pool (0.005 g per g protein)."""
    composite.main([])
    cp = common.read_ini(repo / "outputs" / "composite" / "composite_summary.ini")
    wb = cp["weighting_basis"]
    assert float(wb["muscle_free_g_per_g_protein"]) == pytest.approx(1.18)
    assert float(wb["blood_free_g_per_g_protein"]) == pytest.approx(1.18)
    assert float(wb["muscle_pool_g_per_g_protein"].split(";")[0]) == pytest.approx(0.005)
    assert float(wb["muscle_amino_acid_mass_g"]) == pytest.approx(600 * (1.18 + 0.005))
    assert float(wb["blood_amino_acid_mass_g"]) == pytest.approx(400 * 1.18)
    assert float(cp["histidine"]["composite_g_per_100g"]) == pytest.approx(6.4)
    assert float(cp["masses"]["total_protein_g"]) == pytest.approx(1000.0)


def test_a_profile_that_does_not_sum_to_one_hundred_stops(repo):
    p = repo / "outputs" / "blood" / "blood.tsv"
    p.write_text(p.read_text().replace("10.000000", "12.000000"))
    with pytest.raises(SystemExit, match="sums to"):
        composite.main([])


def test_a_basis_mismatch_stops(repo):
    p = repo / "config" / "pools.ini"
    p.write_text(p.read_text().replace("basis = wet", "basis = dry"))
    with pytest.raises(SystemExit, match="basis"):
        composite.main([])


def test_one_category_is_not_a_composite(repo):
    p = repo / "config" / "tissue_mass_fractions.ini"
    text = p.read_text()
    p.write_text(text[:text.index("[category.blood]")])
    with pytest.raises(SystemExit, match="at least two"):
        composite.main([])
