"""The composition outputs must equal a fresh build from the data on disk.

Skipped when the mass table has not been fetched on this machine
(no data/pubchem/amino_acid_masses.ini) or composition has not been run. Fails if
outputs/composition/* were hand-edited or are stale, if the fetched mass table
lacks a section, or if any residue mass is not free mass minus water.

What the mass-table test checks, in plain terms: the file PubChem produced has all
twenty amino acids plus water and hydrogen, was written by the fetch stage (header
marker), and its residue masses are arithmetic on its own free masses -- so a
hand edit to any one number is caught.
"""
import pytest

from pipeline import common, composition


needs_masses = pytest.mark.skipif(not common.AMINO_ACID_MASSES_INI.exists(),
                                  reason="fetch_amino_acid_masses has not run on this machine")
needs_outputs = pytest.mark.skipif(not common.composition_tsv().exists()
                                   or not common.AMINO_ACID_MASSES_INI.exists()
                                   or not common.SEQUENCES_INI.exists(),
                                   reason="composition has not run on this machine")
upstream_running = pytest.mark.skipif(common.running_command_is_before("composition"),
                                      reason="an earlier command is running; composition is rebuilt by `python run.py composition`")


@needs_masses
def test_mass_table_is_generated_and_consistent():
    text = common.AMINO_ACID_MASSES_INI.read_text(encoding="utf-8")
    assert text.startswith("# amino_acid_masses.ini -- GENERATED by fetch_amino_acid_masses.py")
    m = composition.load_masses()
    for a in common.AMINO_ACIDS:
        assert m["residue"][a] == pytest.approx(m["free"][a] - m["water"], abs=1e-9), a
        assert m["free"][a] > m["water"] > 0


@needs_masses
def test_mass_table_matches_parsed_symbols_and_decisions():
    """Every letter in the mass table carries the name parsed from the IUPAC-IUBMB
    page, the query name obeys the decisions-file rule, and the extras are present."""
    symbols = common.read_ini(common.AMINO_ACID_SYMBOLS_INI)
    dec = common.read_ini(common.COMPOSITION_DECISIONS_INI)
    table = common.read_ini(common.AMINO_ACID_MASSES_INI)
    assert sorted(symbols.sections()) == sorted(common.AMINO_ACIDS)
    extras = [k for k in dec["extra_compounds"] if k != "decision"]
    assert sorted(table.sections()) == sorted(list(common.AMINO_ACIDS) + extras)
    prefix = dec["query_name_rule"]["chiral_prefix"]
    for a in common.AMINO_ACIDS:
        name = symbols[a]["trivial_name"]
        assert table[a]["trivial_name"] == name
        assert table[a]["query_name"] in (prefix + name, name)
        assert table[a]["query_rule"] == ("chiral_prefix" if table[a]["query_name"] == prefix + name else "bare_trivial_name")
        assert table[a]["cid"].isdigit()
    for e in extras:
        assert table[e]["query_name"] == dec["extra_compounds"][e] and table[e]["cid"].isdigit()


@needs_outputs
@upstream_running
def test_composition_outputs_are_current():
    assert composition.main(["--check"]) == 0


@needs_outputs
@upstream_running
def test_composition_covers_every_accession_twice():
    rows = common.read_tsv(common.composition_tsv())
    accessions = common.read_ini(common.ACCESSIONS_INI)
    expected = [a for a in accessions.sections() if accessions[a].get("flag_open") != "true"]
    seen = {}
    for r in rows:
        seen.setdefault(r["accession"], []).append(r["segment_set"])
    assert sorted(seen) == sorted(expected)
    assert all(sorted(v) == ["master", "metabolic"] for v in seen.values())
    for r in rows:
        assert abs(sum(float(r[f"free_frac_{a}"]) for a in common.AMINO_ACIDS) - 1.0) < 1e-6
        assert abs(sum(float(r[f"residue_frac_{a}"]) for a in common.AMINO_ACIDS) - 1.0) < 1e-6
