"""fetch_sequences: JSON extraction and sequence verification, offline."""
import json
import pytest
from conftest import FIXTURES

from pipeline import fetch_sequences as va
from pipeline import common


@pytest.fixture
def entry():
    return json.loads((FIXTURES / "entry_one_chain.json").read_text())


def test_extract_fields(entry):
    rec = va.extract(entry)
    assert rec["accession"] == "X99001" and rec["gene"] == "FIXA"
    assert rec["length"] == "13" and rec["seq_version"] == "2"
    assert [f["type"] for f in rec["features"]] == ["Initiator methionine", "Chain", "Alternative sequence"]
    assert rec["n_features_total"] == "4"
    assert [i["status"] for i in rec["isoforms"]] == ["Displayed", "Described"]
    assert rec["isoforms"][1]["note"].startswith("A free-text note")
    assert [a["term_id"] for a in rec["annotations"]] == ["TEST:0000003", "TEST:0000006"]
    assert rec["annotations"][0]["evidence"] == "IDA:UniProtKB"
    assert rec["tissue_specificity"] == "Recorded, never parsed."


def test_md5_verification_passes_and_fails(entry):
    rec = va.extract(entry)
    assert va.check_sequence(rec, rec["sequence"]) == []
    rec2 = va.extract(entry)
    problems = va.check_sequence(rec2, rec2["sequence"][:-1] + "A")
    assert any("MD5" in p for p in problems) and any("differs" in p for p in problems)


def test_nonstandard_letters_are_recorded_not_failures(entry):
    # R5 (D59): the letters are recorded on the record; build_protein_set excludes and lists the entry
    rec = va.extract(entry)
    rec["sequence"] = "MGGGAAAKKKWWXU"
    rec["length"] = str(len(rec["sequence"]))
    rec["md5_uniprot"] = common.md5_text(rec["sequence"])
    problems = va.check_sequence(rec, rec["sequence"])
    assert problems == [] and rec["non_standard_letters"] == "UX"


def test_md5_matches_uniprot_convention():
    # UniProt publishes the uppercase hex MD5 of the raw sequence string
    assert common.md5_text("MGGGAAAKKKWWY") == "B8BAB4B84AC5F378A79AC603BD2410F4"


def test_section_roundtrip(entry, tmp_path):
    rec = va.extract(entry)
    va.check_sequence(rec, rec["sequence"])
    rec["canonical_isoform_id"] = "X99001-1"
    cp = common.new_ini()
    cp["X99001"] = va.to_section(rec, ["1"])
    p = tmp_path / "v.ini"
    common.write_ini(cp, p, ["test"])
    back = common.read_ini(p)["X99001"]
    assert back["md5_match"] == "true" and back["feature.1.type"] == "Chain"
    assert back["annotation.1.evidence"] == "IEA:Ensembl"


# --------------------------------------------------------------------------- the additive store (D110)

def _store_text(header, sections):
    cp = common.new_ini()
    for name, items in sections.items():
        cp[name] = items
    return common.render_ini(cp, header)


def test_store_text_round_trips_verbatim(tmp_path):
    p = tmp_path / "s.ini"
    text = _store_text(["uniprot_sequences.ini -- GENERATED by fetch_sequences.py. DO NOT EDIT BY HAND.",
                        "fetched         = 2026-01-01T00:00:00Z", "uniprot_release = 2026_03",
                        "source          = https://rest.uniprot.org/uniprotkb/", "captured_feature_types = Chain",
                        "accessions      = 2", "failures        = 0"],
                       {"X00001": {"tiers": "1", "protein_name": "a ; b # c", "sequence": "MKV"},
                        "X00002": {"tiers": "2", "sequence": "MKVA", "note": "[not a section]"}})
    p.write_text(text, encoding="utf-8", newline="\n")
    header, blocks = va.read_store_text(p)
    assert header[0].startswith("uniprot_sequences.ini") and "fetched         = 2026-01-01T00:00:00Z" in header
    assert set(blocks) == {"X00001", "X00002"}
    assert "a ; b # c" in blocks["X00001"]                      # read as text: an inline ';' or '#' survives
    # merging with nothing new reproduces the file byte for byte (a category run that fetched nothing)
    merged = va.merged_store_text(va.merge_header(header, "blood", "2026_04", 0, 2, 0), {}, blocks)
    body = lambda t: t.split("\n\n", 1)[1]                       # noqa: E731 -- everything after the header
    assert body(merged) == body(text)


def test_category_fetch_adds_sections_and_keeps_the_rest(tmp_path):
    header = ["uniprot_sequences.ini -- GENERATED by fetch_sequences.py. DO NOT EDIT BY HAND.",
              "fetched         = 2026-01-01T00:00:00Z", "uniprot_release = 2026_03",
              "source          = https://rest.uniprot.org/uniprotkb/", "captured_feature_types = Chain",
              "accessions      = 1", "failures        = 0"]
    old = _store_text(header, {"X00002": {"tiers": "1", "sequence": "MKV"}})
    hdr, blocks = va.read_store_text(tmp_path / "missing.ini")
    assert hdr == [] and blocks == {}
    p = tmp_path / "s.ini"; p.write_text(old, encoding="utf-8", newline="\n")
    hdr, blocks = va.read_store_text(p)
    new = {"X00001": {"tiers": "plasma", "sequence": "MKVA", "fetched": "2026-09-19T00:00:00Z", "uniprot_release": "2026_04"}}
    text = va.merged_store_text(va.merge_header(hdr, "blood", "2026_04", 1, 2, 0), new, blocks)
    lines = text.splitlines()
    assert lines[0] == "# uniprot_sequences.ini -- GENERATED by fetch_sequences.py. DO NOT EDIT BY HAND."
    assert "# fetched         = 2026-01-01T00:00:00Z" in lines and "# uniprot_release = 2026_03" in lines
    assert any(l.startswith("# added.blood.fetched = ") for l in lines)
    assert "# added.blood.accessions = 1" in lines and "# accessions      = 2" in lines
    assert text.index("[X00001]") < text.index("[X00002]")      # one sorted order
    assert blocks["X00002"] in text                              # the old section, verbatim
    p2 = tmp_path / "m.ini"; p2.write_text(text, encoding="utf-8", newline="\n")
    cp = common.read_ini(p2)
    assert cp["X00001"]["fetched"] == "2026-09-19T00:00:00Z" and cp["X00002"]["tiers"] == "1"
    # a later FULL (muscle) run: its own sections are rendered anew; the section blood added is carried
    hdr2, blocks2 = va.read_store_text(p2)
    text2 = va.merged_store_text(va.merge_header(hdr2, None, "2026_05", 1, 2, 0),
                                 {"X00002": {"tiers": "1", "sequence": "MKV"}},
                                 {n: b for n, b in blocks2.items() if n != "X00002" and "\nfetched " in b})
    assert "[X00001]" in text2 and "# added.blood.accessions = 1" in text2 and "# uniprot_release = 2026_05" in text2
