"""The mass-fraction outputs and generated config must equal a fresh build from the
files on disk. Skipped where the literature has not been fetched on this machine.
Also: the code names no accession, and every weight column of the generated config
(config/mass_fractions_per_entry.tsv, D61) sums to one."""
import re

import pytest

from pipeline import common, mass_fractions as mf

needs_data = pytest.mark.skipif(not mf.MANIFEST_INI.exists() or not (mf.OUT_DIR / "mass_fractions_summary.ini").exists(),
                                reason="literature not fetched or mass_fractions not run on this machine")
upstream_running = pytest.mark.skipif(common.running_command_is_before("mass-fractions"),
                                      reason="an earlier command is running; mass fractions are rebuilt by `python run.py mass-fractions`")


@needs_data
@upstream_running
def test_mass_fraction_outputs_are_current():
    assert mf.main(["--check"]) == 0


@needs_data
@upstream_running
def test_generated_config_sums_to_one_per_tier_and_combined():
    """config/mass_fractions_per_entry.tsv (D61): every within-tier weight column sums to one
    over the tier's members, and every combined column sums to one over all entries."""
    rows = mf.read_tsv_skip_comments(common.MASS_FRACTIONS_TSV)
    assert rows
    cols = [c for c in rows[0] if re.fullmatch(r"w_(I|IIa|IIx)_(tier\d+|combined)", c)]
    assert cols, rows[0].keys()
    for c in cols:
        s = sum(float(r[c]) for r in rows if r[c] != "")
        assert abs(s - 1.0) < 1e-6, (c, s)


@needs_data
@upstream_running
def test_generated_config_is_marked_generated():
    assert common.MASS_FRACTIONS_TSV.read_text(encoding="utf-8").startswith("# GENERATED by mass_fractions.py")


def test_code_names_no_accession():
    acc = re.compile(r"\b(?:[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9](?:[A-Z][A-Z0-9]{2}[0-9]){1,2})\b")
    text = (common.REPO_ROOT / "pipeline" / "mass_fractions.py").read_text(encoding="utf-8")
    hits = [ln for ln in text.splitlines() if acc.search(ln)]
    assert hits == [], hits
