"""Download UniProt's controlled vocabulary of post-translational modifications.

ptmlist.txt is the vocabulary behind every `Modified residue`, `Lipidation`,
`Glycosylation`, and `Cross-link` feature description in UniProtKB. Each record
carries the modification's identifier (ID, the same string that appears in the
feature description), its accession (AC), the feature type it is used in (FT),
and -- for most chemically defined modifications -- the monoisotopic (MM) and
average (MA) mass difference the modification adds to the protein. This stage
only downloads and records; ptm_disclosure.py reads it.

The file is fetched from the UniProt FTP mirror over HTTPS. If that host is not
reachable, the second URL (uniprot.org/docs) is tried. The file is saved unchanged,
hashed, and parsed once here to confirm it has the record structure ptm_disclosure.py
depends on (ID lines, and MA lines on at least some records); any surprise stops
the run with the counts it saw.

Outputs  data/uniprot_ptmlist/ptmlist.txt
         data/uniprot_ptmlist/source.ini   (URL used, retrieval time, SHA-256, record counts)
"""

from __future__ import annotations

import argparse
import sys

import requests

from pipeline import common

STAGE = "fetch_ptmlist"
URLS = [
    "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/ptmlist.txt",
    "https://www.uniprot.org/docs/ptmlist.txt",
]
USER_AGENT = "uniprot-standard/composition (contact: repository README)"


def parse_ptmlist(text: str) -> dict[str, dict[str, list[str]]]:
    """Parse the flat file into {ID: {code: [lines...]}}.

    Records begin at a line starting with 'ID   ' and end at '//'. Every other line
    of a record is '<two-letter code>   <content>'. Lines before the first record
    (the file's own header) are ignored. Pure function; tested offline.
    """
    records: dict[str, dict[str, list[str]]] = {}
    current: dict[str, list[str]] | None = None
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if line.startswith("ID   "):
            current = {"ID": [line[5:].strip()]}
            continue
        if current is None:
            continue
        if line.startswith("//"):
            rid = current["ID"][0]
            if rid in records:
                raise ValueError(f"duplicate ID in ptmlist: {rid!r}")
            records[rid] = current
            current = None
            continue
        if len(line) >= 5 and line[2:5] == "   ":
            current.setdefault(line[:2], []).append(line[5:].strip())
    return records


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.parse_args(argv)
    log = common.make_logger(STAGE)
    session = requests.Session()
    session.headers["User-Agent"] = USER_AGENT

    content, used = None, None
    for url in URLS:
        try:
            resp = session.get(url, timeout=120)
        except requests.RequestException as exc:
            log.warning("%s -> %s", url, exc)
            continue
        if resp.status_code == 200 and resp.content:
            content, used = resp.content, url
            break
        log.warning("%s -> HTTP %d", url, resp.status_code)
    if content is None:
        log.error("could not download ptmlist.txt from any of %s", URLS)
        return 1

    common.PTMLIST_TXT.parent.mkdir(parents=True, exist_ok=True)
    common.PTMLIST_TXT.write_bytes(content)
    sha = common.sha256_file(common.PTMLIST_TXT)
    records = parse_ptmlist(content.decode("utf-8", errors="replace"))
    n_ma = sum(1 for r in records.values() if r.get("MA"))
    n_ft = {}
    for r in records.values():
        for ft in r.get("FT", []):
            n_ft[ft] = n_ft.get(ft, 0) + 1
    if not records or n_ma == 0:
        log.error("ptmlist.txt parsed to %d records, %d with an MA line -- format not as expected; stopping",
                  len(records), n_ma)
        return 1

    src = common.new_ini()
    src["ptmlist"] = {
        "url": used,
        "retrieved": common.iso_now(),
        "sha256": sha,
        "bytes": str(len(content)),
        "records": str(len(records)),
        "records_with_average_mass": str(n_ma),
        "records_by_feature_type": "; ".join(f"{k}={v}" for k, v in sorted(n_ft.items())),
    }
    common.write_ini(src, common.PTMLIST_TXT.parent / "source.ini",
                     ["source.ini -- GENERATED by fetch_ptmlist.py. DO NOT EDIT BY HAND.",
                      "Provenance of data/uniprot_ptmlist/ptmlist.txt."])
    log.info("ptmlist.txt: %d bytes, sha256 %s, %d records (%d with MA) from %s", len(content), sha, len(records), n_ma, used)
    return 0


if __name__ == "__main__":
    sys.exit(main())
